name: xa-transaction-tutorial
services:
  postgresql:
    image: docker.io/postgres:17
    healthcheck:
      test: pg_isready -U quarkus -d customers_db
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: customers_db
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Quarkus123!'
      MSSQL_LOGGING: "verbose"
      MSSQL_PID: "Developer"
    ports: 
      - "1433:1433"
    labels:
      io.quarkus.devservices.compose.jdbc.parameters: trustServerCertificate=true